louvre_resa_booking:
    path:     /
    defaults:
        _controller: LouvreResaBundle:Resa:booking 
    
louvre_resa_command:
    path:     /command/{code}
    defaults:
        _controller: LouvreResaBundle:Resa:command 
        
louvre_resa_payement:
    path:     /payement/{code}
    defaults:
        _controller: LouvreResaBundle:Resa:payement
        
louvre_resa_confirmation:
    path:     /confirmation
    defaults:
        _controller: LouvreResaBundle:Resa:confirmation
        
louvre_resa_test:
    path:     /test
    defaults:
        _controller: LouvreResaBundle:Resa:test 
