<?php

namespace Louvre\ResaBundle\Repository;

/**
 * BookingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookingRepository extends \Doctrine\ORM\EntityRepository
{
    public function lastBooking() 
    {
        $queryBuilder = $this
            ->createQueryBuilder('b')
            ->where('b.ticketCommand IS NULL')
            ->orderBy('b.id', 'desc')
            ->setMaxResults(1);

        $query = $queryBuilder->getQuery();
        $results = $query->getResult()[0];

        return $results;
    }
    
    public function deleteUnfinished() 
    {
        /*
        $queryBuilder = $this
            ->createQuery('DELETE Booking b WHERE b.ticketCommand IS NULL')
            ->execute();*/
        
        $queryBuilder = $this
            ->createQueryBuilder('b')
            ->delete('Louvre\ResaBundle\Entity\Booking', 'b')
            ->where('b.ticketCommand IS NULL')
            ->getQuery()
            ->execute();
    }
    
}
