<?php

namespace Louvre\ResaBundle\Repository;

/**
 * TicketRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketRepository extends \Doctrine\ORM\EntityRepository
{
    public function lastTickets() 
    {
        $queryBuilder = $this
            ->createQueryBuilder('b')
            ->where('b.ticketCommand IS NULL')
            ->orderBy('b.id', 'desc');

        $query = $queryBuilder->getQuery();
        $results = $query->getResult();

        return $results;
    }
}
