<?php

namespace Louvre\ResaBundle\Repository;

/**
 * TicketCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TicketCommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function lastTicketCommand() 
    {
        $queryBuilder = $this
            ->createQueryBuilder('t')
            ->orderBy('t.id', 'desc')
            ->setMaxResults(1);
        
        $query = $queryBuilder->getQuery();
        $results = $query->getResult()[0];
        
        return $results;
    }
}
